# Move this to ~/.config/fish/config.fish
alias "gs"="git status"
alias "gl"="git log"
alias "gcl"="git checkout -"
alias "gml"="git merge -"
alias "poo"="start *.sln"
alias "gsu"="git submodule update --init --recursive"
alias "gd"="git diff"
alias "gmum"="git merge upstream/master"
alias "gmud"="git merge upstream/dev"
alias "gfa"="git fetch --all"
alias "grpo"="git remote prune origin"
alias "shazaam"="gfa;gmum;gsu;git push"
alias "shazoom"="gfa;gmud;gsu;git push"
alias "pip"="pip3"
